
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('expenses').del()
    .then(function () {
      // Inserts seed entries
      return knex('expenses').insert([
        {expense_description: 'Food', 
expense_amount: '1000', 
expense_spender_id: 1, 
expense_reason: 'Groceries', 
expense_details: 'Frys', 
expense_date: '1/1/2019', 
expense_paid: true,  
expense_credited: true},
        {expense_description: 'Gasoline',  
expense_amount: '200', 
expense_spender_id: 1, 
expense_reason: 'Both cars commute', 
expense_details: 'Circle K', 
expense_date: '1/1/2019', 
expense_paid: false,  
expense_credited: true},
        {expense_description: 'Mortgage',  
expense_amount: '860', 
expense_spender_id: 1, 
expense_reason: 'Shelter', 
expense_details: 'Fifth Third Bank', 
expense_date: '1/1/2019', 
expense_paid: true,  
expense_credited: true},
{expense_description: 'Entertainment',  
expense_amount: '3000', 
expense_spender_id: 1, 
expense_reason: 'Drinks', 
expense_details: 'Got shitfaced', 
expense_date: '1/1/2019', 
expense_paid: false,  
expense_credited: true},
{expense_description: 'Emergency',  
expense_amount: '3000', 
expense_spender_id: 2, 
expense_reason: 'HVAC', 
expense_details: 'Heater repair', 
expense_date: '1/1/2019', 
expense_paid: true,  
expense_credited: true},
{expense_description: 'Pool pump',  
expense_amount: '500', 
expense_spender_id: 4, 
expense_reason: 'Repair', 
expense_details: 'Purchased refurbished', 
expense_date: '1/1/2019', expense_paid: true,  
expense_credited: true},
{expense_description: 'Auto Insurance',  
expense_amount: '600', 
expense_spender_id: 2, 
expense_reason: 'Hard drive', 
expense_details: 'Western Digital 2TB Server grade', 
expense_date: '1/1/2019', 
expense_paid: true,  
expense_credited: true},
{expense_description: 'Bike tire tubes',  
expense_amount: '30', 
expense_spender_id: 3, 
expense_reason: 'flat tire', 
expense_details: 'Walmart', 
expense_date: '1/1/2019', 
expense_paid: true,  
expense_credited: true},
{expense_description: 'Veterinarian',  
expense_amount: '1000', 
expense_spender_id: 3, 
expense_reason: 'Dude euthanasia', 
expense_details: 'Camelback Animal Hospital', 
expense_date: '1/1/2019', 
expense_paid: true,  
expense_credited: true}
      ]);
    });
};
